#baseURL = 'http://localhost:1313/'
baseURL = 'https://viewportui.com/'
languageCode = 'en-us'
title = 'Viewport UI - UI curated experiences for you inspiration.'

[params]
  alternateBaseURL = 'https://viewport-ui.design/'

[taxonomies]
tag = "tags"
category = "categories"

[menu]
    [[menu.categories]]
        name = "All"
        url = "/"
        weight = 1
    [[menu.categories]]
        name = "Web"
        url = "/categories/web"
        weight = 2
    [[menu.categories]]
        name = "Desktop"
        url = "/categories/desktop"
        weight = 3
    [[menu.categories]]
        name = "Mobile"
        url = "/categories/mobile"
        weight = 4
    [[menu.categories]]
        name = "Watch"
        url = "/categories/watch"
        weight = 5
    [[menu.categories]]
        name = "iOS"
        url = "/categories/ios"
        weight = 6
    [[menu.categories]]
        name = "Android"
        url = "/categories/android"
        weight = 7
    [[menu.categories]]
        name = "Icon"
        url = "/categories/icon"
        weight = 8
    [[menu.categories]]
        name = "Motion"
        url = "/categories/motion"
        weight = 9