#baseURL = 'http://localhost:1313/'
baseURL = 'https://viewport-ui.design/'
languageCode = 'en-us'
title = 'Viewport UI - UI curated experiences for you inspiration.'

[taxonomies]
tag = "tags"

[menu]
    [[menu.tags]]
        name = "All"
        url = "/"
        weight = 1
    [[menu.tags]]
        name = "Watch"
        url = "/tags/watch"
        weight = 2
    [[menu.tags]]
        name = "Mobile"
        url = "/tags/mobile"
        weight = 3
    [[menu.tags]]
        name = "Desktop"
        url = "/tags/desktop"
        weight = 4
    [[menu.tags]]
        name = "iOS"
        url = "/tags/ios"
        weight = 5
    [[menu.tags]]
        name = "Android"
        url = "/tags/android"
        weight = 6
    [[menu.tags]]
        name = "Icon"
        url = "/tags/icon"
        weight = 7
    [[menu.tags]]
        name = "Motion"
        url = "/tags/motion"
        weight = 8